steps:
  - name: 'maven:3.8.6-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package']

# Enable automatic regional log bucket creation
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - gcr.io/fresh-bloom-438819-i4/spring-boot-rest:${SHORT_SHA}
